[node]
port = 8545
rest_port = 8546
data_dir = "~/.scopenode"
era_dir = "~/era1"

[[contracts]]
name = "Uniswap V3 ETH/USDC"
address = "0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8"
events = ["Swap"]
from_block = 25000000
to_block = 25010000
abi_override = "./abis/UniswapV3Pool.json"
