//! JSON-RPC method implementations.
//!
//! Only contracts that have been indexed (present in the `contracts` table in SQLite)
//! are served. Requests for unindexed contracts return a human-readable error
//! pointing to `scopenode status` so users understand what's available.
//!
//! All methods are backed by SQLite queries — there is no in-memory cache. For
//! typical usage patterns (low QPS, small result sets), SQLite is fast enough.
//!
//! # Served methods
//! - `eth_getLogs` — filtered event log query
//! - `eth_blockNumber` — highest indexed block
//! - `eth_chainId` — always `0x1` (Ethereum mainnet)
//! - `eth_subscribe` — WebSocket push subscriptions: `"logs"` and `"newHeads"`
//! - `eth_unsubscribe` — cancel a subscription (wired automatically by jsonrpsee)

use std::time::Duration;

use alloy::rpc::types::{Filter, Log};
use alloy_primitives::{Address, Bytes, B256};
use async_trait::async_trait;
use jsonrpsee::core::{to_json_raw_value, RpcResult, SubscriptionResult};
use jsonrpsee::proc_macros::rpc;
use jsonrpsee::types::ErrorObject;
use jsonrpsee::PendingSubscriptionSink;
use scopenode_core::types::StoredEvent;
use scopenode_storage::Db;
use tokio::sync::broadcast;
use tracing::warn;

/// The subset of the Ethereum JSON-RPC API that scopenode serves.
///
/// Generated by the `#[rpc(server, namespace = "eth")]` proc macro, which
/// creates the `EthApiServer` trait and wires up the JSON-RPC dispatch.
#[rpc(server, namespace = "eth")]
pub trait EthApi {
    /// `eth_getLogs` — query event logs matching a filter.
    #[method(name = "getLogs")]
    async fn get_logs(&self, filter: Filter) -> RpcResult<Vec<Log>>;

    /// `eth_blockNumber` — return the highest indexed block number as hex.
    #[method(name = "blockNumber")]
    async fn block_number(&self) -> RpcResult<String>;

    /// `eth_chainId` — return the chain ID as hex.
    #[method(name = "chainId")]
    async fn chain_id(&self) -> RpcResult<String>;

    /// `eth_subscribe` — subscribe to live events or new block headers over WebSocket.
    ///
    /// Supported subscription types:
    /// - `"logs"` — push each indexed event; optional filter: `{address, topics: [topic0]}`
    /// - `"newHeads"` — push a block header for every processed block
    ///
    /// `eth_unsubscribe` is wired automatically by jsonrpsee.
    #[subscription(name = "subscribe", unsubscribe = "unsubscribe", item = serde_json::Value)]
    async fn subscribe(
        &self,
        sub_type: String,
        filter: Option<serde_json::Value>,
    ) -> SubscriptionResult;
}

/// Implementation of the Ethereum JSON-RPC interface backed by SQLite.
///
/// Holds a reference-counted `Db` handle (cheap to clone). All query methods
/// delegate directly to `Db` without additional caching.
pub struct EthApiImpl {
    db: Db,
    broadcast: broadcast::Sender<StoredEvent>,
    headers: broadcast::Sender<(u64, B256, u64)>,
}

impl EthApiImpl {
    /// Create a new `EthApiImpl` backed by the given database and broadcast channels.
    pub fn new(
        db: Db,
        broadcast: broadcast::Sender<StoredEvent>,
        headers: broadcast::Sender<(u64, B256, u64)>,
    ) -> Self {
        Self { db, broadcast, headers }
    }
}

#[async_trait]
impl EthApiServer for EthApiImpl {
    /// `eth_getLogs` implementation.
    async fn get_logs(&self, filter: Filter) -> RpcResult<Vec<Log>> {
        let address: Option<Address> = filter.address.iter().next().copied();

        let in_scope = if let Some(addr) = address {
            self.db
                .is_contract_indexed(&addr.to_checksum(None))
                .await
                .unwrap_or(false)
        } else {
            false
        };

        if !in_scope {
            return Err(not_indexed_error());
        }

        let contract_str: Option<String> = address.map(|a: Address| a.to_checksum(None));
        let from_block = filter.get_from_block();
        let to_block = filter.get_to_block();

        let topic0_str: Option<String> = filter
            .topics
            .first()
            .and_then(|t| t.iter().next())
            .map(|t| format!("{:?}", t));

        let rows = self
            .db
            .query_events_for_filter(
                contract_str.as_deref(),
                None,
                topic0_str.as_deref(),
                from_block,
                to_block,
                10_000,
                0,
            )
            .await
            .map_err(|e| internal_error(&e.to_string()))?;

        let logs = rows
            .into_iter()
            .filter_map(|row| row_to_log(&row))
            .collect();

        Ok(logs)
    }

    /// `eth_blockNumber` — return the highest block number in our headers table.
    async fn block_number(&self) -> RpcResult<String> {
        let n = self
            .db
            .latest_block_number()
            .await
            .map_err(|e| internal_error(&e.to_string()))?;
        Ok(format!("0x{:x}", n.unwrap_or(0)))
    }

    /// `eth_chainId` — always returns `0x1` (Ethereum mainnet).
    async fn chain_id(&self) -> RpcResult<String> {
        Ok("0x1".into())
    }

    /// `eth_subscribe` — WebSocket push subscriptions.
    ///
    /// Dispatches to the appropriate broadcast channel based on `sub_type`.
    /// Slow clients that lag more than the channel capacity will miss events
    /// but the subscription stays open (matching the SSE policy in rest.rs).
    async fn subscribe(
        &self,
        pending: PendingSubscriptionSink,
        sub_type: String,
        filter: Option<serde_json::Value>,
    ) -> SubscriptionResult {
        match sub_type.as_str() {
            "logs" => {
                let sink = pending.accept().await?;
                let mut rx = self.broadcast.subscribe();

                // Parse optional address and topic0 filters; normalize to lowercase.
                let addr_filter = filter
                    .as_ref()
                    .and_then(|f| f["address"].as_str())
                    .map(|s| s.to_lowercase());
                let topic0_filter = filter
                    .as_ref()
                    .and_then(|f| f["topics"][0].as_str())
                    .map(|s| s.to_lowercase());

                loop {
                    let event = match rx.recv().await {
                        Ok(e) => e,
                        Err(broadcast::error::RecvError::Lagged(n)) => {
                            warn!(n, "eth_subscribe logs: subscriber lagged, events dropped");
                            continue;
                        }
                        Err(broadcast::error::RecvError::Closed) => break,
                    };

                    if !logs_matches(&event, addr_filter.as_deref(), topic0_filter.as_deref()) {
                        continue;
                    }

                    let val = event_to_log_json(&event);
                    let msg = match to_json_raw_value(&val) {
                        Ok(m) => m,
                        Err(e) => {
                            warn!("eth_subscribe logs: serialization error: {e}");
                            continue;
                        }
                    };
                    if sink.send_timeout(msg, Duration::from_secs(5)).await.is_err() {
                        break;
                    }
                }
            }
            "newHeads" => {
                let sink = pending.accept().await?;
                let mut rx = self.headers.subscribe();
                // Per-subscriber state — not shared across concurrent subscribers.
                let mut last_seen_block: u64 = 0;

                loop {
                    let (block_number, block_hash, timestamp) = match rx.recv().await {
                        Ok(h) => h,
                        Err(broadcast::error::RecvError::Lagged(n)) => {
                            warn!(n, "eth_subscribe newHeads: subscriber lagged, headers dropped");
                            continue;
                        }
                        Err(broadcast::error::RecvError::Closed) => break,
                    };

                    if block_number <= last_seen_block {
                        continue;
                    }
                    last_seen_block = block_number;

                    let val = serde_json::json!({
                        "blockNumber": format!("0x{:x}", block_number),
                        "blockHash":   format!("{:?}", block_hash),
                        "timestamp":   format!("0x{:x}", timestamp),
                    });
                    let msg = match to_json_raw_value(&val) {
                        Ok(m) => m,
                        Err(e) => {
                            warn!("eth_subscribe newHeads: serialization error: {e}");
                            continue;
                        }
                    };
                    if sink.send_timeout(msg, Duration::from_secs(5)).await.is_err() {
                        break;
                    }
                }
            }
            other => {
                pending
                    .reject(ErrorObject::owned(
                        -32602,
                        format!("unsupported subscription type: {other:?}"),
                        None::<()>,
                    ))
                    .await;
            }
        }

        Ok(())
    }
}

// ── Filter helper ─────────────────────────────────────────────────────────────

/// Returns `true` when `event` passes the optional address and topic0 filters.
///
/// Both comparisons are case-insensitive (caller must pass lowercased filters).
fn logs_matches(
    event: &StoredEvent,
    addr_filter: Option<&str>,
    topic0_filter: Option<&str>,
) -> bool {
    if let Some(addr) = addr_filter {
        if event.contract.to_checksum(None).to_lowercase() != addr {
            return false;
        }
    }
    if let Some(t0) = topic0_filter {
        if format!("{:?}", event.topic0).to_lowercase() != t0 {
            return false;
        }
    }
    true
}

// ── Serialization helpers ─────────────────────────────────────────────────────

/// Serialize a core `StoredEvent` into the Ethereum `eth_getLogs` Log JSON shape.
fn event_to_log_json(event: &StoredEvent) -> serde_json::Value {
    let topics: Vec<String> = std::iter::once(format!("{:?}", event.topic0))
        .chain(event.raw_topics.iter().skip(1).map(|t| format!("{:?}", t)))
        .collect();

    serde_json::json!({
        "address":          event.contract.to_checksum(None),
        "topics":           topics,
        "data":             format!("0x{}", hex::encode(&event.raw_data)),
        "blockNumber":      format!("0x{:x}", event.block_number),
        "blockHash":        format!("{:?}", event.block_hash),
        "transactionHash":  format!("{:?}", event.tx_hash),
        "transactionIndex": format!("0x{:x}", event.tx_index),
        "logIndex":         format!("0x{:x}", event.log_index),
        "removed":          false,
    })
}

// ── JSON-RPC error helpers ────────────────────────────────────────────────────

fn not_indexed_error() -> ErrorObject<'static> {
    ErrorObject::owned(
        -32000,
        "Contract not indexed. Run `scopenode status` to see what's indexed.",
        None::<()>,
    )
}

fn internal_error(msg: &str) -> ErrorObject<'static> {
    ErrorObject::owned(-32603, format!("Internal error: {msg}"), None::<()>)
}

// ── row_to_log (for eth_getLogs) ──────────────────────────────────────────────

/// Convert a [`StoredEvent`] row from SQLite into an alloy [`Log`] type.
fn row_to_log(row: &scopenode_storage::models::StoredEvent) -> Option<Log> {
    use alloy::primitives::LogData;

    let address: Address = row.contract.parse().ok()?;
    let tx_hash: B256 = row.tx_hash.parse().ok()?;
    let block_hash: B256 = row.block_hash.parse().ok()?;

    let topics: Vec<B256> = serde_json::from_str::<Vec<String>>(&row.raw_topics)
        .ok()?
        .iter()
        .filter_map(|t| t.parse().ok())
        .collect();

    let data_bytes = alloy_primitives::hex::decode(&row.raw_data).unwrap_or_default();
    let data = Bytes::from(data_bytes);

    let log_data = LogData::new(topics, data)?;

    let inner_log = alloy::primitives::Log {
        address,
        data: log_data,
    };

    Some(Log {
        inner: inner_log,
        block_hash: Some(block_hash),
        block_number: Some(row.block_number as u64),
        block_timestamp: None,
        transaction_hash: Some(tx_hash),
        transaction_index: Some(row.tx_index as u64),
        log_index: Some(row.log_index as u64),
        removed: false,
    })
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::{Address, Bytes};
    use tokio::sync::broadcast;

    fn make_event(contract: Address, event_name: &str, topic0: B256) -> StoredEvent {
        StoredEvent {
            contract,
            event_name: event_name.to_string(),
            topic0,
            block_number: 1,
            block_hash: B256::ZERO,
            tx_hash: B256::ZERO,
            tx_index: 0,
            log_index: 0,
            raw_topics: vec![topic0],
            raw_data: Bytes::default(),
            decoded: serde_json::json!({}),
            source: "devp2p".to_string(),
            timestamp: 0,
        }
    }

    #[test]
    fn logs_matches_no_filter_passes_all() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let ev = make_event(addr, "Transfer", B256::ZERO);
        assert!(logs_matches(&ev, None, None));
    }

    #[test]
    fn logs_matches_address_filter_passes_exact() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let ev = make_event(addr, "Transfer", B256::ZERO);
        let filter = addr.to_checksum(None).to_lowercase();
        assert!(logs_matches(&ev, Some(&filter), None));
    }

    #[test]
    fn logs_matches_address_filter_blocks_other() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let other = "0x0000000000000000000000000000000000000001";
        let ev = make_event(addr, "Transfer", B256::ZERO);
        assert!(!logs_matches(&ev, Some(other), None));
    }

    #[test]
    fn logs_matches_topic0_filter_passes_matching() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let topic0 = B256::from([1u8; 32]);
        let ev = make_event(addr, "Transfer", topic0);
        let filter = format!("{:?}", topic0).to_lowercase();
        assert!(logs_matches(&ev, None, Some(&filter)));
    }

    #[test]
    fn logs_matches_topic0_filter_blocks_other() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let topic0 = B256::from([1u8; 32]);
        let other_t0 = B256::from([2u8; 32]);
        let ev = make_event(addr, "Transfer", topic0);
        let filter = format!("{:?}", other_t0).to_lowercase();
        assert!(!logs_matches(&ev, None, Some(&filter)));
    }

    #[test]
    fn event_to_log_json_has_expected_keys() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let ev = make_event(addr, "Transfer", B256::ZERO);
        let json = event_to_log_json(&ev);
        for key in &["address", "topics", "data", "blockNumber", "blockHash",
                     "transactionHash", "transactionIndex", "logIndex", "removed"] {
            assert!(json.get(key).is_some(), "missing key: {key}");
        }
        assert_eq!(json["removed"], false);
        assert_eq!(json["blockNumber"], "0x1");
    }

    /// Broadcast channel fans events to all subscribers (including WS subscriptions).
    #[tokio::test]
    async fn broadcast_fan_out_reaches_all_ws_subscribers() {
        let addr: Address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48".parse().unwrap();
        let (tx, mut rx1) = broadcast::channel::<StoredEvent>(8);
        let mut rx2 = tx.subscribe();

        tx.send(make_event(addr, "Transfer", B256::ZERO)).unwrap();

        let e1 = rx1.recv().await.unwrap();
        let e2 = rx2.recv().await.unwrap();
        assert_eq!(e1.event_name, "Transfer");
        assert_eq!(e2.event_name, "Transfer");
    }
}
