//! JSON-RPC method implementations.
//!
//! Only contracts that have been indexed (present in the `contracts` table in SQLite)
//! are served. Requests for unindexed contracts return a human-readable error
//! pointing to `scopenode status` so users understand what's available.
//!
//! All methods are backed by SQLite queries — there is no in-memory cache. For
//! typical usage patterns (low QPS, small result sets), SQLite is fast enough.
//! Phase 3 may add an LRU cache if needed.
//!
//! # Served methods
//! - `eth_getLogs` — filtered event log query
//! - `eth_blockNumber` — highest indexed block
//! - `eth_chainId` — always `0x1` (Ethereum mainnet)

use alloy::rpc::types::{Filter, Log};
use alloy_primitives::{Address, Bytes, B256};
use async_trait::async_trait;
use jsonrpsee::core::RpcResult;
use jsonrpsee::proc_macros::rpc;
use jsonrpsee::types::ErrorObject;
use scopenode_storage::Db;

/// The subset of the Ethereum JSON-RPC API that scopenode serves.
///
/// Generated by the `#[rpc(server, namespace = "eth")]` proc macro, which
/// creates the `EthApiServer` trait and wires up the JSON-RPC dispatch.
#[rpc(server, namespace = "eth")]
pub trait EthApi {
    /// `eth_getLogs` — query event logs matching a filter.
    #[method(name = "getLogs")]
    async fn get_logs(&self, filter: Filter) -> RpcResult<Vec<Log>>;

    /// `eth_blockNumber` — return the highest indexed block number as hex.
    #[method(name = "blockNumber")]
    async fn block_number(&self) -> RpcResult<String>;

    /// `eth_chainId` — return the chain ID as hex.
    #[method(name = "chainId")]
    async fn chain_id(&self) -> RpcResult<String>;
}

/// Implementation of the Ethereum JSON-RPC interface backed by SQLite.
///
/// Holds a reference-counted `Db` handle (cheap to clone). All query methods
/// delegate directly to `Db` without additional caching.
pub struct EthApiImpl {
    db: Db,
}

impl EthApiImpl {
    /// Create a new `EthApiImpl` backed by the given database.
    pub fn new(db: Db) -> Self {
        Self { db }
    }
}

#[async_trait]
impl EthApiServer for EthApiImpl {
    /// `eth_getLogs` implementation.
    ///
    /// Checks if the queried contract is indexed; if not, returns a clear error
    /// message telling the user to run `scopenode status`. Translates the filter
    /// into a SQL query and maps the results to alloy `Log` types.
    ///
    /// Only returns non-reorged events. Caps results at 10,000 rows to protect
    /// against oversized responses.
    async fn get_logs(&self, filter: Filter) -> RpcResult<Vec<Log>> {
        // Extract the first address from the filter to check if it's indexed.
        let address: Option<Address> = filter.address.iter().next().copied();

        let in_scope = if let Some(addr) = address {
            self.db
                .is_contract_indexed(&addr.to_checksum(None))
                .await
                .unwrap_or(false)
        } else {
            false
        };

        if !in_scope {
            return Err(not_indexed_error());
        }

        let contract_str: Option<String> = address.map(|a: Address| a.to_checksum(None));
        let from_block = filter.get_from_block();
        let to_block = filter.get_to_block();

        // Extract topic0 from the filter if provided — used to narrow the query to
        // a specific event type. topic0 = keccak256(event signature), e.g. for
        // Transfer(address,address,uint256) it's 0xddf252ad...
        // If multiple topic0 values are given (OR semantics), we take the first only —
        // multi-topic OR queries are rare and add significant query complexity.
        let topic0_str: Option<String> = filter
            .topics
            .first()
            .and_then(|t| t.iter().next())
            .map(|t| format!("{:?}", t));

        let rows = self
            .db
            .query_events_for_filter(
                contract_str.as_deref(),
                None,           // event_name: JSON-RPC uses topic0, not name
                topic0_str.as_deref(),
                from_block,
                to_block,
                10_000, // Safety cap: prevent response size explosions.
                0,      // offset: not used from JSON-RPC path
            )
            .await
            .map_err(|e| internal_error(&e.to_string()))?;

        let logs = rows
            .into_iter()
            .filter_map(|row| row_to_log(&row))
            .collect();

        Ok(logs)
    }

    /// `eth_blockNumber` — return the highest block number in our headers table.
    ///
    /// The value reflects how far scopenode has synced, not the current chain tip.
    /// Returned as a `0x`-prefixed hex string per the Ethereum JSON-RPC spec.
    async fn block_number(&self) -> RpcResult<String> {
        let n = self
            .db
            .latest_block_number()
            .await
            .map_err(|e| internal_error(&e.to_string()))?;
        Ok(format!("0x{:x}", n.unwrap_or(0)))
    }

    /// `eth_chainId` — always returns `0x1` (Ethereum mainnet).
    ///
    /// Phase 2 could make this dynamic based on the config. For now, scopenode
    /// only supports mainnet (chain ID 1).
    async fn chain_id(&self) -> RpcResult<String> {
        Ok("0x1".into())
    }
}

/// JSON-RPC error returned when the queried contract hasn't been indexed.
///
/// Error code `-32000` is in the standard range for application-level errors
/// (as opposed to protocol errors like `-32700` parse error or `-32601` method
/// not found). The message is intentionally actionable.
fn not_indexed_error() -> ErrorObject<'static> {
    ErrorObject::owned(
        -32000,
        "Contract not indexed. Run `scopenode status` to see what's indexed.",
        None::<()>,
    )
}

/// JSON-RPC internal error (`-32603`) for unexpected failures.
///
/// Used when a DB query fails unexpectedly. The error message includes the
/// underlying cause for debugging.
fn internal_error(msg: &str) -> ErrorObject<'static> {
    ErrorObject::owned(-32603, format!("Internal error: {msg}"), None::<()>)
}

/// Convert a [`StoredEvent`] row from SQLite into an alloy [`Log`] type.
///
/// Returns `None` if any field can't be parsed (e.g. a corrupt hex string in the DB).
/// Well-formed data should never fail here since the pipeline validates fields on insert.
fn row_to_log(row: &scopenode_storage::models::StoredEvent) -> Option<Log> {
    use alloy::primitives::LogData;

    let address: Address = row.contract.parse().ok()?;
    let tx_hash: B256 = row.tx_hash.parse().ok()?;
    let block_hash: B256 = row.block_hash.parse().ok()?;

    // Parse topics from the JSON array stored in raw_topics.
    // The array contains hex strings like ["0xddf252...", "0x0000...sender", ...].
    let topics: Vec<B256> = serde_json::from_str::<Vec<String>>(&row.raw_topics)
        .ok()?
        .iter()
        .filter_map(|t| t.parse().ok())
        .collect();

    // Parse the raw ABI-encoded data from its hex string representation.
    let data_bytes = alloy_primitives::hex::decode(&row.raw_data).unwrap_or_default();
    let data = Bytes::from(data_bytes);

    // `LogData::new` validates that topics.len() <= 4 (EVM constraint).
    let log_data = LogData::new(topics, data)?;

    let inner_log = alloy::primitives::Log {
        address,
        data: log_data,
    };

    Some(Log {
        inner: inner_log,
        block_hash: Some(block_hash),
        block_number: Some(row.block_number as u64),
        block_timestamp: None,
        transaction_hash: Some(tx_hash),
        transaction_index: Some(row.tx_index as u64),
        log_index: Some(row.log_index as u64),
        removed: false,
    })
}
